### ISSUE TITLE
libwine.so.1 too short

### ISSUE THREAD

**Issue by ccgauvin94** [rawfoxDE/raw-wine#1]
Hi, 
Thank you for all the work. Unfortunately, when I try to run the game, I receive this error: 
```
~/.local/share/lutris/runners/wine/raw-wine/bin/wine: error while loading shared libraries: ~/.local/share/lutris/runners/wine/raw-wine/bin/../lib/libwine.so.1: file too short
Waiting on children
Exit with returncode 127
```

**Comment by beniwtv** [comment]
If you have downloaded the zip file, this won't work, as symlinks are not supported in zip files.
You need to clone the repository with "git clone" instead.
