### ISSUE TITLE
sources or included patches?

### ISSUE THREAD

**Issue by char32** [rawfoxDE/raw-wine#2]
First: Thanks for all the work in putting those builds together!

I just wanted to ask if the sources are available anywhere?
Or if there is a list like wine staging 6.15 + patch A + patch B, etc.?
In order to reproduce the build.

Thanks!

**Comment by rawfoxDE** [comment]
The runners i do are as unmodified as possible. 
If a unmodified wine-staging can not run StarCitizen, then modifications come in place, to make it work. 
In that process we (#LUG) find a lot of bugs, wich help to improve wine as well as SC, so in general i post the patches wich are in as well as commenting, what has been done to make it work with SC.
The source i use is from the official wine and wine-staging git repos, so there is no need to post them here again.
My runners are just container builds of a most original wine-staging for downwards compatibility to lower glibc versions, so they run on a wider range of distros.
There is a couple other #LUG members, who do runners as well. Some are more experimental, containing partly more exotic patches and all that, if you want to try another runner, we made a tool to support you using the different runners our members provide and care for some system checks to give you a good SC experience. 
You can find that tool here: https://github.com/the-sane/lug-helper

**Comment by char32** [comment]
Perfect! Thanks a lot for the detailed explanation.
